name = "qwertylock-api"
main = "src/worker.js"
compatibility_date = "2026-06-04"

routes = [
  { pattern = "lock.slendystuff.com", custom_domain = true }
]

[vars]
PUBLIC_TOOL_URL = "https://slendystuff.com/r/"

[[durable_objects.bindings]]
name = "QLOCK_MESSAGE"
class_name = "QwertyLockMessage"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["QwertyLockMessage"]
